### ISSUE TITLE
"Wrong zoom" in some cases

### ISSUE THREAD

**Issue by ragazzojp** [CartoDB/quadbin-js#14]
I get "Wrong zoom" error in same cases.

For example, with `resolution` 5 and `geometry`:

```json
{
    "type": "Polygon",
    "coordinates": [
        [
            [
                -242.0778956585969,
                -85.05112877980662
            ],
            [
                228.9610653803646,
                -85.05112877980662
            ],
            [
                228.9610653803646,
                85.0511287798066
            ],
            [
                -242.0778956585969,
                85.0511287798066
            ],
            [
                -242.0778956585969,
                -85.05112877980662
            ]
        ]
    ]
}
```

**Comment by Jesus89** [comment]
The polygon seems out of range

**Comment by felixpalmer** [comment]
I think in this case you should cut your geometry into valid (non-overlapping) chunks and make several requests to the function. 

It isn't clear what the behavior in this case should be, which is why it is better for the calling code to explictly handle it. I.e. should the cells in the overlapping regions be returned twice or should the returned list be unique?

**Comment by ragazzojp** [comment]
Fair enough. Closed as invalid.
